In [1]:
print(" arun sarathi")



 arun sarathi


## Arrays

In [2]:
import numpy as np

In [3]:
x = [2,3,4,5,6]       #  1D array

In [4]:
np.array(x)

array([2, 3, 4, 5, 6])

In [5]:
print(x)

[2, 3, 4, 5, 6]


In [6]:
type(x)

list

In [7]:
data =np.array(x)

In [8]:
data

array([2, 3, 4, 5, 6])

In [9]:
data.astype

<function ndarray.astype>

In [10]:
data.ndim

1

In [11]:
data.shape

# it include s chara

(5,)

In [12]:
# 2d array
data_2d = np.array([[2,4,6,8],[1,3,5,7]])


In [13]:
data_2d

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [14]:
data_2d.astype

<function ndarray.astype>

In [15]:
data_2d.ndim

2

In [16]:
data_2d.shape

(2, 4)

In [17]:
# 2 row
# 4 collm

In [18]:
# zero, one ,empty arroys

In [19]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
arrays_comp = np.ones((5,6,3))
# 5 matirx 6 rows 3 colm

In [24]:
arrays_comp

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
np.ones((5,6,3,2,4))  # no.of value is rep 5D

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

    

In [26]:
arr_empty = np.empty((3,3,4))

In [27]:
arr_empty


array([[[3.15088788e+156, 8.73762705e+183, 6.01346953e-154,
         7.19498123e+159],
        [7.34350295e+271, 2.41702714e-152, 5.29339457e+180,
         2.35288464e+251],
        [2.88854907e+214, 1.14421598e+243, 2.46599062e-154,
         2.88527118e+214]],

       [[1.77860494e-104, 1.16995827e+171, 7.20191272e+159,
         1.24805535e+243],
        [3.62481991e+228, 1.06112832e-153, 2.31633953e-152,
         2.44085569e-154],
        [3.58251187e+246, 8.71280277e+183, 8.78420982e+247,
         5.04620678e+180]],

       [[6.72794694e+199, 1.71431207e+161, 1.00863407e+261,
         3.44618946e-085],
        [6.60240843e+180, 2.35037512e+180, 2.93283336e+222,
         3.98837334e+252],
        [6.01433264e+175, 6.62277974e+265, 1.27874046e-152,
         1.69375350e+190]]])

In [28]:
np.arange(12)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
np.arange(2,40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [30]:
np.arange(2,40,5)
# dif 5

array([ 2,  7, 12, 17, 22, 27, 32, 37])

In [31]:
# data type
data=np.array(np.arange(2,40,6),dtype = np.int32)

In [32]:
data

array([ 2,  8, 14, 20, 26, 32, 38])

In [33]:
# data type
data=np.array(np.arange(2,40,6),dtype = np.float64)

In [34]:
data

array([ 2.,  8., 14., 20., 26., 32., 38.])

In [35]:
data.dtype

dtype('float64')

In [36]:
# Operations on Arrays

In [37]:
array1 = np.array([[2,4,6],[1,3,5]])

array2 = np.array([[12,14,16],[13,15,17]])

In [38]:
array1 +array1


array([[ 4,  8, 12],
       [ 2,  6, 10]])

In [39]:
array2 + array1

array([[14, 18, 22],
       [14, 18, 22]])

In [40]:
array2 - array1

array([[10, 10, 10],
       [12, 12, 12]])

In [41]:
array2 * array1

array([[24, 56, 96],
       [13, 45, 85]])

In [42]:
array1

array([[2, 4, 6],
       [1, 3, 5]])

In [43]:
array1 * 2

array([[ 4,  8, 12],
       [ 2,  6, 10]])

In [44]:
array1 ** 3

# 2^3 = 8

array([[  8,  64, 216],
       [  1,  27, 125]], dtype=int32)

## indexing and slicing

In [45]:

data=np.array(np.arange(2,40,6),dtype = np.int32)

In [46]:
data

array([ 2,  8, 14, 20, 26, 32, 38])

In [47]:
data[4]
#[ 2,  8, 14, 20, 26, 32, 38])
# 0,   1,  2,  3,  4,  5,  6
# -7,  -6, -5  -4  -3  -2  -1  

26

In [48]:
data[-1]

38

In [49]:
data[-2]

32

In [50]:
data[1:3]

array([ 8, 14])

In [51]:
data[:3]

array([ 2,  8, 14])

In [52]:
data[3:]

array([20, 26, 32, 38])

In [53]:
data

array([ 2,  8, 14, 20, 26, 32, 38])

In [54]:
# add
data[3:9] = 16
data

array([ 2,  8, 14, 16, 16, 16, 16])

In [55]:

data=np.array(np.arange(2,40,6),dtype = np.int32)

In [56]:
data


array([ 2,  8, 14, 20, 26, 32, 38])

In [57]:
data_1 =data[:3]

In [58]:
data_1

array([ 2,  8, 14])

In [59]:
data[0] =100

In [60]:
data

array([100,   8,  14,  20,  26,  32,  38])

In [61]:
# 2d

In [62]:
array2 = np.array([[2,4,6],[1,3,5],[22,23,34],[13,15,19]])

In [63]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [64]:
array2[0]

array([2, 4, 6])

In [65]:
array2[2]

array([22, 23, 34])

In [66]:
array2[-2]

array([22, 23, 34])

In [67]:
array2[0][0]

2

In [68]:
array2[0][1]

4

In [69]:
# 23
array2[2][1]

23

In [70]:
array2[2,1]

23

In [71]:
array2[1:3]

array([[ 1,  3,  5],
       [22, 23, 34]])

In [72]:
array2

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [22, 23, 34],
       [13, 15, 19]])

In [73]:
array2[:2][:2]

array([[2, 4, 6],
       [1, 3, 5]])

In [74]:
array2[:2][1:3]

array([[1, 3, 5]])

In [17]:
name = 'Arun'
age = 20
height = 6.5
print(name)
print(age)
print(height)


Arun
20
6.5


## counter

In [78]:
import collections


In [79]:
collections.Counter(['x','y','x','z','x','y','x','x','y','z','y','x'])

Counter({'x': 6, 'y': 4, 'z': 2})

In [80]:
collections.Counter({'x': 6, 'y': 4, 'v': 2})

Counter({'x': 6, 'y': 4, 'v': 2})

In [81]:
collections.Counter(x=4, y=2, z=5, v=3)

Counter({'x': 4, 'y': 2, 'z': 5, 'v': 3})

In [84]:
list1= ['z','b','c','x','y','z','x','a','x','b']


In [85]:
collections.Counter(list1)

Counter({'z': 2, 'b': 2, 'c': 1, 'x': 3, 'y': 1, 'a': 1})

In [88]:
list2 = ('arun sarathi')

In [89]:
collections.Counter(list2)

Counter({'a': 3,
         'r': 2,
         'u': 1,
         'n': 1,
         ' ': 1,
         's': 1,
         't': 1,
         'h': 1,
         'i': 1})

In [90]:
x = collections.Counter()

In [91]:
x

Counter()

In [92]:
x.update('1515484515121354223484646646848786515315')

In [93]:
x

Counter({'1': 7, '5': 8, '4': 8, '8': 5, '2': 3, '3': 3, '6': 5, '7': 1})

In [96]:
for numbers in x:
    print( "{} = {}".format(numbers,x[numbers]))

1 = 7
5 = 8
4 = 8
8 = 5
2 = 3
3 = 3
6 = 5
7 = 1


In [97]:
for numbers in '123456789':
    print( "{} = {}".format(numbers,x[numbers]))

1 = 7
2 = 3
3 = 3
4 = 8
5 = 8
6 = 5
7 = 1
8 = 5
9 = 0


In [98]:
x = collections.deque('hijklmn')

In [99]:
x

deque(['h', 'i', 'j', 'k', 'l', 'm', 'n'])

In [100]:
# add chra
x.extendleft('g')

In [101]:
x


deque(['g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'])

In [102]:
x.extendleft('arun')

In [103]:
x

deque(['n', 'u', 'r', 'a', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'])

In [105]:
x.extend('kl')

In [106]:
x

deque(['n', 'u', 'r', 'a', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'k', 'l'])

In [107]:
#  remove chara
x.pop()

'l'

In [108]:
x

deque(['n', 'u', 'r', 'a', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'k'])

In [109]:
x.popleft()

'n'

In [110]:
x

deque(['u', 'r', 'a', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'k'])

In [111]:
# add chara
x.appendleft('rst')

In [112]:
x

deque(['rst', 'u', 'r', 'a', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'k'])

In [113]:
# list multiplication add list

In [114]:
list1 = [1,2,3,4,5,6]
cubes = []

In [116]:
for numbers in list1:
    cubes.append(numbers**3)

In [117]:
cubes

[1, 8, 27, 64, 125, 216]

In [130]:
sqrt =[]
list2 = [1, 8, 27, 64, 125, 216]

In [131]:
for numbers in list2:
    sqrt.append(numbers**.5)

In [132]:
sqrt

[1.0,
 2.8284271247461903,
 5.196152422706632,
 8.0,
 11.180339887498949,
 14.696938456699069]

## For Loops

In [144]:
list_num = [2,3,4,5]

In [145]:
for numbers in list_num:
    print (numbers)

2
3
4
5


In [146]:
for numbers in sqrt:
    print (numbers)

1.0
2.8284271247461903
5.196152422706632
8.0
11.180339887498949
14.696938456699069


In [157]:
number_list = range(0,29)

In [158]:
number_list

range(0, 29)

In [159]:
for numbers in list(range(0,22)):
    print (numbers)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [160]:
print(number_list)

range(0, 29)


In [161]:
for x in number_list:
    print (x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28


In [168]:
for num in number_list:
    if num% 3 == 0:
        print(num , "number devisible by 3")

0 number devisible by 3
3 number devisible by 3
6 number devisible by 3
9 number devisible by 3
12 number devisible by 3
15 number devisible by 3
18 number devisible by 3
21 number devisible by 3
24 number devisible by 3
27 number devisible by 3


In [170]:
for num in number_list:
    if num% 6 == 0:
        print(num)
        print("number devisible by 6")

0
number devisible by 6
6
number devisible by 6
12
number devisible by 6
18
number devisible by 6
24
number devisible by 6


In [171]:
items = ['item1', 'item2', 'item3', 'item4']

In [173]:
for i in range(len(items)):
    print("item at index", str(i) ,"is: ", items[i])

item at index 0 is:  item1
item at index 1 is:  item2
item at index 2 is:  item3
item at index 3 is:  item4


In [176]:
for name in "Arun Sarathi":
    print (name)

A
r
u
n
 
S
a
r
a
t
h
i


## Funtions in python

In [178]:
def subtract(x, y):
    print(x - y)
    
subtract(12, 5)

7


In [179]:
subtract(5,7)

-2


In [181]:
def subtract(x, y):
    print(x-y)
    
a = subtract(4,3)

1


In [182]:
def subtract(x, y):
    return x - y

subtract(4,3)

1

## Lambda Functions !! & Map function

In [183]:
def difference(x,y):
    return x-y

In [184]:
difference(4,5)

-1

In [185]:
a = lambda x,y: x-y

In [186]:
a(4,5)

-1

In [187]:
def summation(a,b,c):
    return a+b+c

In [188]:
summation(3,4,5)

12

In [189]:
summ = lambda a,b,c: a+b+c

In [190]:
summ(3,4,5)

12

In [12]:
def power(x):
    return x**2

In [13]:
power(5)

25

In [14]:
power(6)

36

In [15]:
x = [3,6,9,12]

In [16]:
list(map(lambda y: y*y, x))

[9, 36, 81, 144]